---
- name: Install dependencies for building KEA
  apt:
    state: present
    name: "{{item}}"
    update_cache: yes
  with_items:
    - build-essential
    - libssl-dev
    - liblog4cplus-dev
    - libcurl4-openssl-dev
    - libboost-all-dev

- name: Create required directories
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{kea_build_path}}"
    - "{{kea_path}}/bin"
    - "{{kea_path}}/logs"

- name: Check public addr
  set_fact:
    kea_mr_provisioner_public_addr: "{{mr_provisioner_public_addr|default('127.0.0.1')}}"

- name: Check if KEA has been built
  stat:
    path: "{{kea_path}}/sbin/kea-dhcp4"
  register: kea

- name: Get KEA source code
  unarchive:
    src: "{{item}}"
    dest: "{{kea_build_path}}"
    remote_src: yes
  with_items:
    - "https://ftp.isc.org/isc/kea/{{kea_version}}/kea-{{kea_version}}.tar.gz"
  when: kea.stat.exists == False

- name: Build and install KEA
  shell: "cd {{kea_build_path}}/kea-{{kea_version}}/ && ./configure --prefix={{kea_path}} && make -j && make install"
  register: build
  fail_when: build.rc != 0
  when: kea.stat.exists == False

- name: Fetch mr-provisioner KEA plugin
  unarchive:
    src: "{{item}}"
    dest: "{{kea_build_path}}"
    remote_src: yes
  with_items:
    - "https://github.com/Linaro/mr-provisioner-kea/archive/v{{kea_mr_provisioner_plugin_version}}.tar.gz"

- name: Build and install mr-provisioner KEA plugin
  make:
    chdir: "{{kea_build_path}}/mr-provisioner-kea-{{kea_mr_provisioner_plugin_version}}"
    target: install
    params:
      KEA_SRC: "{{kea_build_path}}/kea-{{kea_version}}"
      KEA_PREFIX: "{{kea_path}}"

- name: Generate configuration files for KEA
  template:
    src: templates/kea.conf.j2
    dest: "{{kea_config}}"

- name: Install the KEA services
  template:
    src: "{{item}}.service.j2"
    dest: "/etc/systemd/system/{{item}}.service"
  with_items:
    - "{{kea_services}}"

- name: Start the KEA services
  systemd:
    state: restarted
    name: "{{item}}"
    daemon_reload: yes
    enabled: yes
  with_items:
    - "{{kea_services}}"
